### ISSUE TITLE
Check email on redemption

### ISSUE THREAD

**Issue by mjuneja** [vinsol-spree-contrib/spree_gift_card#22]
When a gift card is redeemed, should the system check that the user redeeming the card has the same email id to which the gift card was mailed by the purchaser of the gift card.

Not sure if it is happening right now. If not, then should this check be added ?

**Comment by jatin-baweja** [comment]
@mjuneja : Thanks for the suggestion. It's being fixed in 3-1-dev. It will soon be merged in 3-1-stable. Will inform you when it's done.

**Comment by jatin-baweja** [comment]
We've merged the user check into 3-1-stable. Thanks for the suggestion. :)
