### ISSUE TITLE
Coupon Code vs Gift Code bug?

### ISSUE THREAD

**Issue by jkelleyj** [vinsol-spree-contrib/spree_gift_card#23]
Is this line:

```
if params[:order] && params[:order][:gift_code]
  @order.coupon_code = params[:order][:gift_code]
end
```

Supposed to read:

```
if params[:order] && params[:order][:gift_code]
  @order.gift_code = params[:order][:gift_code]
end
```

https://github.com/vinsol-spree-contrib/spree_gift_card/blob/master/app/controllers/spree/store_controller_decorator.rb#L7

It immediately exists unless gift_code is set, so I'm assuming this is a bug?

**Comment by nishant-cyro** [comment]
Thanks @jkelleyj for the issue. It has been resolved in the latest version of the extension.
