### ISSUE TITLE
Order Contents Decorator undefined method 'grab_line_item_by_variant'

### ISSUE THREAD

**Issue by Mbuckley0** [vinsol-spree-contrib/spree_gift_card#49]
When using spree 3.7.0 it fails to run with gem due to "grab_line_item_by_variant" no longer being a method in the order contents model.

**Comment by Umair-Liaqat-ALi** [comment]
+1

**Comment by zainrafique** [comment]
+1

**Comment by manishrawat0212** [comment]
Hey @Mbuckley0 
Spree 3.7 support is now available in https://github.com/vinsol-spree-contrib/spree_gift_card/tree/3-7-stable branch
Let us know if you face any issues with this branch
